name: Build and Push Artifacts

on:
  push:
    branches:
      - main  # Trigger on changes to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: logging
        run: |
            ls
            echo "Build job completed."
      - name: build
        run : npm run build
      - name: console again
        run: |
            ls
            echo "Build job completed again."