name: "Deploy to AWS"
on:
  workflow_run:
    workflows:
      - Build and Push Artifacts
    types:
      - completed
    

permissions:
  actions: read      
  contents: read

jobs:
  deploy:
    environment: production
    if: ${{github.event.workflow_run.conclusion == 'success'}}   
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/
          run-id: ${{github.event.workflow_run.id}}
          github-token: ${{github.token}}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.EC2_SSH_KEY}}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.EC2_HOST}} >> ~/.ssh/known_hosts

      - name : Copy files to EC2
        run: scp -r build/*  ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}}:~/app
      
        
      - name : Login to EC2
        env: 

          env_vars: |
            DATABASE_URL = ${{secrets.DATABASE_URL}}
            BASE_PATH = ${{secrets.BASE_PATH}}
            PORT= ${{secrets.PORT}}

            MAILER_HOST= ${{secrets.MAILER_HOST}}
            MAILER_PORT= ${{secrets.MAILER_PORT}}
            MAILER_MAIL= ${{secrets.MAILER_MAIL}}
            MAILER_PASSWORD= ${{secrets.MAILER_PASSWORD}}
            MAILER_SERVICE= ${{secrets.MAILER_SERVICE}}
            JWT_SECRET=${{secrets.JWT_SECRET}}
            JWT_EXPIRES_IN= ${{secrets.JWT_EXPIRES_IN}}

            STRIPE_KEY= ${{secrets.STRIPE_KEY}}
            STRIPE_WEBHOOK= ${{secrets.STRIPE_WEBHOOK}}

            AWS_ACCESS_KEY_ID= ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
            S3_BUCKET_NAME=${{secrets.S3_BUCKET_NAME}}
            AWS_REGION=${{secrets.AWS_REGION}}
            FIREBASE_SECRETS=${{secrets.FIREBASE_SECRETS}}

        run: |
          ssh ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}} << EOF
          cd app
          touch .env
          echo "${env_vars}" > .env
          pnpm install
          pm2 restart dist/src/main.js
          EOF